"""Constants and configuration shared across modules."""
from __future__ import annotations

from cuesheet_creator import (
    DEFAULT_COLUMN_WIDTHS,
    LOCAL_FFMPEG_BIN_ENV,
    LOCAL_FFMPEG_SEARCH_ROOT,
    MOTION_ALIASES,
    MOTION_ENUM,
    NAMING_CATEGORY_FIELDS,
    NAMING_REPLACE_FIELDS,
    OPTIONAL_COMPONENTS,
    PREPARE_ENV_MODES,
    REQUIRED_PACKAGES,
    SHOT_SIZE_ALIASES,
    SHOT_SIZE_ENUM,
    SKILL_ROOT,
    SUPPORTED_OPTIONAL_GROUPS,
    TEMPLATE_COLUMNS,
    TEMPLATE_SCHEMA_VERSION,
)

__all__ = [
    "REQUIRED_PACKAGES", "OPTIONAL_COMPONENTS", "TEMPLATE_COLUMNS",
    "TEMPLATE_SCHEMA_VERSION", "DEFAULT_COLUMN_WIDTHS",
    "SUPPORTED_OPTIONAL_GROUPS", "PREPARE_ENV_MODES",
    "SKILL_ROOT", "LOCAL_FFMPEG_BIN_ENV", "LOCAL_FFMPEG_SEARCH_ROOT",
    "NAMING_REPLACE_FIELDS", "NAMING_CATEGORY_FIELDS",
    "SHOT_SIZE_ENUM", "SHOT_SIZE_ALIASES", "MOTION_ENUM", "MOTION_ALIASES",
]
